window.translations = window.translations || {};
window.translations.ja = {
    nav_about: "概要", nav_works: "作品", nav_social: "ソーシャル", nav_advertise: "広告", nav_contact: "連絡",
    hero_greeting: "こんにちは、",
    hero_sub: "デジタルクリエイター / 柴犬ケモノ / 生活芸術の探求者",
    hero_intro_title: "プロフィール",
    hero_intro_content: "私は焦月です、ファーリーです。人を噛むのが好きですが、噛めない時は自分を噛みます😅",
    furry_title: "私のケモノ設定",
    furry_label_name: "名前:", furry_val_name: "焦月 (Jiao Yue)",
    furry_label_species: "種族:", furry_val_species: "柴犬 (Shiba Inu)",
    furry_label_features: "特徴:", furry_val_features: "温かい灰色の毛皮と尻尾を持っています。",
    furry_label_personality: "性格:", furry_val_personality: "好奇心旺盛、友達思い、でもとても恥ずかしがり屋。",
    birthday_title: "誕生日のカウントダウン",
    birthday_label: "誕生日",
    time_days: "日", time_hours: "時", time_minutes: "分", time_seconds: "秒",
    title_works: "注目作品", title_social: "SNSチャンネル",
    work1_title: "YouTube 動画", work1_desc: "YouTubeに投稿したすべての動画作品を収録しています。", work1_btn: "YouTubeチャンネルへ",
    work2_title: "デジタル作品", work2_desc: "最近のデジタルイラスト作品を展示しています。", work2_btn: "PENUPで見る",
    work3_title: "その他の作品", work3_desc: "その他のデジタルイラスト作品を展示しています。", work3_btn: "PENUPで見る",
    title_advertise: "広告掲載",
    advertiser1_name: "Asteroid Host", advertiser1_desc: "無料のホスティングサービス", advertiser1_btn: "サイトへ",
    advertiser2_name: "DiamondHost", advertiser2_desc: "Minecraftサーバーホスティングの最良の選択。クーポンコード「鑽鑽」で特別割引！", advertiser2_btn: "サイトへ",
    advertiser3_name: "CoffeeHost", advertiser3_desc: "Minecraft統合版サーバーホスティングの最良の選択。", advertiser3_btn: "サイトへ",
    footer_slogan: "© 2024 焦月. 創造性でネットの隅々を照らします。",
    lang_choice: "言語選択", current_lang: "日本語"
};
